### ISSUE TITLE
Add a mab_each binder?

### ISSUE THREAD

**Issue by phochste** [jorol/Catmandu-MAB2#3]
Maybe an easy addition to make to Catmandu::MAB2 the mab_each fix like in: https://github.com/LibreCat/Catmandu-MARC/blob/master/lib/Catmandu/Fix/Bind/marc_each.pm

Say you want to apply a fix only if an  e-subfield is available in the MAB file

     do mab_each
         if mab_match("500e",".*")
               fix()
               fix()
               ...
         end
     end

This would be hard to do when the 500 is a repeated field and you only want a fix for that 500 with an $e subfield.

**Comment by jorol** [comment]
Thanks. Implemented in the new release.

**Comment by phochste** [comment]
Super! Thanks
